### ISSUE TITLE
Support for Capacitor v3 and up

### ISSUE THREAD

**Issue by rs2-davebanguilan** [newlogic/smartscanner-capacitor#13]
## Current Behaviour

Only supports Capacitor v2.

## Expected Behaviour

Support for Capacitor v3 and up

## Steps to Reproduce the Problem

1. Use version 3 or 4 of capacitor
2. Run `npm i @idpass/smartscanner-capacitor`
3. Error will show that the package uses capacitor `peer @capacitor/core@"^2.4.1" from @idpass/smartscanner-capacitor@0.4.5-beta`

## Context

Capacitor 3 info:
![image](https://user-images.githubusercontent.com/107235131/208053474-0b731ba7-02bf-4f92-b0b5-fb671083651f.png)

Capacitor 4 info (Latest):
![image](https://user-images.githubusercontent.com/107235131/208053613-6ae70e88-6a18-4a82-90ee-96fb238a3a17.png)

**Comment by rs2-davebanguilan** [comment]
I was able to update it to capacitor v3. Tested the functionality in android and it works fine. I noticed that it only supports the `mrz` even though I changed the mode to `nfc-scan` . How can I change this to `nfc-scan`?

**Comment by megaxayda** [comment]
hi @rs2-davebanguilan , there is a release for v4 recently, you can try it 
https://github.com/newlogic/smartscanner-capacitor/releases/tag/v0.5.0-beta.6
nfc-scan should be working.

**Comment by rs2-davebanguilan** [comment]
Thank you @megaxayda!

**Comment by rs2-davebanguilan** [comment]
Hi @megaxayda , currently experiencing this: 
![image](https://user-images.githubusercontent.com/107235131/208420179-e49d64e6-61e4-4d3b-8cdb-597ae8051b69.png)
