### ISSUE TITLE
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.

### ISSUE THREAD

**Issue by spencerAEE** [newlogic/smartscanner-capacitor#19]
## Current Behaviour

Building an application with Capacitor v4 and React, when I try to create a simple test page I'm getting this error. 

Full message:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':idpass-smartscanner-capacitor' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.10
Update plugins
Affected Modules: app

When clicking on "Update plugins" it goes to a refactor tab but doesn't actually do anything.

## Expected Behaviour

A test application should compile and run allowing me to try out the basic functionality.

## Steps to Reproduce the Problem

1. Use Capacitor v4
2. Build and sync your project
3. Open in Android Studio and sync Gradle

## Solution

Change buildscript.ext.kotlin_version to "1.5.20" in build.gradle

## Context

Windows 11, Node LTS, Android Studio 2022.1.1 (Electric Eel), Gradle 7.4.1. 

- Version: 0.5.0-beta.9
- Platform: Node
- Capacitor version: 4.6.3

**Comment by ccerdaz** [comment]
The same happens to me.

**Comment by spencerAEE** [comment]
I was able to solve it by editing the value in the buildscript object but now there appears to be an issue with dependencies, which I have opened in a separate issue.

**Comment by ccerdaz** [comment]
Thank you
